### ISSUE TITLE
Battery indicator changes continually and rapidly.

### ISSUE THREAD

**Issue by CaMer0n** [TB-Electronics/fscan#2]
![fullsizerender_battery](https://cloud.githubusercontent.com/assets/2825679/25752076/0424e2dc-316c-11e7-90ae-b0581ed612fa.jpg)

**Comment by goldengel** [comment]
The indicator should be stable on original delivered charger when no frequency output is active. Otherwise it can change. For example on 5Hz output on low battery or PC connected (low Power) it can change the indicator.

**Comment by CaMer0n** [comment]
Indeed, it was connected to the PC.
